apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
        - name: mi-app
          image: miacrlucia.azurecr.io/mi-app:latest # esta imaggen debe existir en tu ACR
          ports:
            - containerPort: 3000
